{
 "title": "Myosin Performance Metrics",
 "description": "Performance metrics from myosin runtime.",
 "tags": [ "myosin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Contexts",
   "type": "timeseries",
   "description": "Number of concurrent threads inside state context manager",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "myosin_active_contexts", "legendFormat": "Active Contexts" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Myosin install version",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myosin_meta_info", "legendFormat": "v{{version}}" }
   ]
  },
  {
   "title": "Callback Exception Count",
   "type": "stat",
   "description": "Asynchronous callback exception counter",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myosin_cb_exc_count", "legendFormat": "{{model}}" }
   ]
  },
  { "title": "Checkout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Checkout Latency",
   "type": "timeseries",
   "description": "Average checkout latency per second.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(myosin_checkout_latency_sum[$__rate_interval]) / rate(myosin_checkout_latency_count[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Checkout Request Rate",
   "type": "timeseries",
   "description": "Average checkout requests per second.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(myosin_checkout_latency_count[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "Commit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Commit Latency",
   "type": "timeseries",
   "description": "Average commit latency per second.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(myosin_commit_latency_sum[$__rate_interval]) / rate(myosin_commit_latency_count[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Commit Request Rate",
   "type": "timeseries",
   "description": "Average commit requests per second.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(myosin_commit_latency_count[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Cache Latency",
   "type": "timeseries",
   "description": "Average cache request latency per second.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(myosin_cache_latency_sum[$__rate_interval]) / rate(myosin_cache_latency_count[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Cache Request Rate",
   "type": "timeseries",
   "description": "Average cache requests per second per second.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(myosin_cache_latency_count[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}