---
name: deploy
on:
  release:
    types: [published]

jobs:
  pypi:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
      - name: install dependancies
        run: python3 -m pip install twine
      - name: build package
        run: ./scripts/build.sh -r ${{ github.ref }}
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
